# Generated by Django 5.0.6 on 2024-07-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('Content', models.CharField(default='', max_length=500)),
                ('summary', models.CharField(default='', max_length=1500)),
                ('image', models.ImageField(upload_to='static/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.category')),
            ],
        ),
    ]
