# Generated by Django 5.0.6 on 2024-07-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Content',
            new_name='content',
        ),
    ]
