# Generated by Django 5.0.6 on 2024-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0003_rename_content_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='', max_length=5500),
        ),
    ]
